# -*- coding: utf-8 -*-
"""basic_unstructured_rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/athina-ai/rag-cookbooks/blob/main/advanced_rag_techniques/basic_unstructured_rag.ipynb

# **Unstructured RAG**
Unstructured or (Semi-Structured) RAG is a method designed to handle documents that combine text, tables, and images. It addresses challenges like broken tables caused by text splitting and the difficulty of embedding tables for semantic search.

Here we are using unstructured.io to parse and separate text, tables, and images.

Tool Reference: [Unstructured](https://unstructured.io/)

## **Initial Setup**
"""

! pip install --q athina faiss-gpu pytesseract unstructured-client "unstructured[all-docs]"

!apt-get install poppler-utils
!apt-get install tesseract-ocr
!apt-get install libtesseract-dev

import os
from google.colab import userdata
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
os.environ['ATHINA_API_KEY'] = userdata.get('ATHINA_API_KEY')

"""## **Indexing**"""

# load embedding model
from langchain_openai import OpenAIEmbeddings
embeddings = OpenAIEmbeddings()

# load and extract images, tables, and chunk text
from unstructured.partition.pdf import partition_pdf

filename = "/content/sample.pdf"

pdf_elements = partition_pdf(
    filename=filename,
    extract_images_in_pdf=True,
    strategy = "hi_res",
    hi_res_model_name="yolox",
    infer_table_structure=True,
    chunking_strategy="by_title",
    max_characters=3000,
    combine_text_under_n_chars=200,
)

# check unique categories
from collections import Counter
category_counts = Counter(str(type(element)) for element in pdf_elements)
unique_categories = set(category_counts)
category_counts

# extract unique types
unique_types = {el.to_dict()['type'] for el in pdf_elements}
unique_types

# # display images from pdf
# from IPython.display import Image, display
# image_files = os.listdir('/content/figures')
# image_files = [os.path.join('/content/figures', image_file) for image_file in image_files]

# for image_file in image_files:
#     display(Image(filename=image_file))

# convert pdf_elements to langchain documents
from langchain.schema import Document
documents = [Document(page_content=el.text, metadata={"source": filename}) for el in pdf_elements]

"""## **Vector Store**"""

# create vectorstore
from langchain.vectorstores import FAISS
vectorstore = FAISS.from_documents(documents, embeddings)

"""## **Retriever**"""

# create retriever
retriever = vectorstore.as_retriever()

"""## **RAG Chain**"""

# load llm
from langchain_openai import ChatOpenAI
llm = ChatOpenAI()

# create document chain
from langchain.prompts import ChatPromptTemplate
from langchain.schema.runnable import RunnablePassthrough
from langchain.schema.output_parser import StrOutputParser

template = """"
You are a helpful assistant that answers questions based on the provided context, which can include text and tables.
Use the provided context to answer the question.
Question: {input}
Context: {context}
Answer:
"""
prompt = ChatPromptTemplate.from_template(template)

# Setup RAG pipeline
rag_chain = (
    {"context": retriever,  "input": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

# response
response = rag_chain.invoke("Compare all the Training Results on MATH Test Set")
response

"""## **Preparing Data for Evaluation**"""

# create dataset
question = ["Compare all the Training Results on MATH Test Set"]
response = []
contexts = []

# Inference
for query in question:
  response.append(rag_chain.invoke(query))
  contexts.append([docs.page_content for docs in retriever.get_relevant_documents(query)])

# To dict
data = {
    "query": question,
    "response": response,
    "context": contexts,
}

# create dataset
from datasets import Dataset
dataset = Dataset.from_dict(data)

# create dataframe
import pandas as pd
df = pd.DataFrame(dataset)

df

# Convert to dictionary
df_dict = df.to_dict(orient='records')

# Convert context to list
for record in df_dict:
    if not isinstance(record.get('context'), list):
        if record.get('context') is None:
            record['context'] = []
        else:
            record['context'] = [record['context']]

"""## **Evaluation in Athina AI**

We will use **Does Response Answer Query** eval here. It Checks if the response answer the user's query. To learn more about this. Please refer to our [documentation](https://docs.athina.ai/api-reference/evals/preset-evals/overview) for further details.
"""

# set api keys for Athina evals
from athina.keys import AthinaApiKey, OpenAiApiKey
OpenAiApiKey.set_key(os.getenv('OPENAI_API_KEY'))
AthinaApiKey.set_key(os.getenv('ATHINA_API_KEY'))

# load dataset
from athina.loaders import Loader
dataset = Loader().load_dict(df_dict)

# evaluate
from athina.evals import DoesResponseAnswerQuery
DoesResponseAnswerQuery(model="gpt-4o").run_batch(data=dataset).to_df()